# @package lerobot.dataset

id: libero_5pct
repo_id: hlrp/libero_5pct_multitask_only
mix_path: config/stage3_dataset_mix/libero_5pct_multitask_only.yaml
episodes: null
root: null
revision: null
use_imagenet_stats: false
video_backend: pyav
