# @package _group_

id: multitask_scratch
logging_tags: ["stage3", "lerobot", "libero", "hlrp-policy", "smolvla", "scratch", "cotrain"]
batch_size: 32

policy:
  repo_id: felixmin/hlrp_smolvla_shared_libero_cotrain_scratch
  stage3_training_mode: multitask
  action_subset_ratio: 1.0
  latent_scope: all
  lam_checkpoint_path: /mnt/data/workspace/code/high-level-robot-planner/runs/2026-02-24_10-41-51_lam_oxe_local/checkpoints/last.ckpt
  lam_future_frames: 10
  lam_camera_keys: [observation.images.image]
